#!/bin/bash
set -euo pipefail

VALIDATOR_INDEX=${VALIDATOR_INDEX:-0}
VALIDATOR_COUNT=${VALIDATOR_COUNT:-0}
IS_BOOTSTRAP=${IS_BOOTSTRAP:-false}
BOOTSTRAP_PEERS=${BOOTSTRAP_PEERS:-""}
CHAIN_ID=${CHAIN_ID:-1337}
DATA_DIR=${DATA_DIR:-/data}
SHARED_DIR=${SHARED_DIR:-/shared}
BARRIER_DIR=${BARRIER_DIR:-/barrier}

RUNTIME_DIR=${KORA_RUNTIME_DIR:-/runtime}

# Cap Tokio and Rayon thread counts to avoid oversubscription.
# Inside Docker, Tokio/Rayon read the HOST CPU count (e.g. 12) rather than
# the cgroup limit (e.g. 2 CPUs), creating massive context switching overhead.
# The default of 8 Tokio workers provides enough async concurrency for
# consensus pipelining, networking, and I/O without extreme oversubscription.
# Rayon is used only for BLS batch verification; 2 threads match the strategy
# parameter (NZUsize!(2)) in runner.rs.
export TOKIO_WORKER_THREADS="${TOKIO_WORKER_THREADS:-8}"
export RAYON_NUM_THREADS="${RAYON_NUM_THREADS:-2}"

MODE="${1:-validator}"
shift || true

log() { echo "[entrypoint] $*"; }
error() { echo "[entrypoint] ERROR: $*" >&2; exit 1; }

# ── Generate config.toml from environment variables ──────────────────────
# Produces /tmp/config.toml so that the kora binary picks up runtime
# tuning (dialable_addr, worker_threads, gas_limit, etc.) without
# requiring a pre-baked config file in the image.
# Write to /tmp (tmpfs) since the rootfs may be read-only (read_only: true
# in compose). /etc/kora is on the rootfs and therefore not writable.
CONFIG_FILE="/tmp/config.toml"

generate_config() {
    log "Generating ${CONFIG_FILE} from environment variables"

    local dialable_section=""
    if [[ -n "${KORA_DIALABLE_ADDR:-}" ]]; then
        dialable_section="dialable_addr = \"${KORA_DIALABLE_ADDR}\""
    fi

    local worker_threads_line=""
    if [[ -n "${KORA_WORKER_THREADS:-}" ]]; then
        worker_threads_line="worker_threads = ${KORA_WORKER_THREADS}"
    fi

    local gas_limit_line=""
    if [[ -n "${KORA_GAS_LIMIT:-}" ]]; then
        gas_limit_line="gas_limit = ${KORA_GAS_LIMIT}"
    fi

    local fee_recipient_line=""
    if [[ -n "${KORA_FEE_RECIPIENT:-}" ]]; then
        fee_recipient_line="fee_recipient = \"${KORA_FEE_RECIPIENT}\""
    fi

    cat > "${CONFIG_FILE}" <<TOML
# Auto-generated by entrypoint.sh — do not edit manually.
# Override values via environment variables (KORA_*).

chain_id = ${CHAIN_ID:-1337}
data_dir = "${DATA_DIR}"
${worker_threads_line}

[network]
listen_addr = "0.0.0.0:30303"
${dialable_section}

[execution]
${gas_limit_line}
${fee_recipient_line}

[rpc]
http_addr = "0.0.0.0:8545"
ws_addr = "0.0.0.0:8546"
TOML

    log "Config written to ${CONFIG_FILE}"
}

# Generate the config file for all modes except raw pass-through.
if [[ "$MODE" != "setup" ]]; then
    generate_config
fi

# Wait for at least one bootstrap peer from a comma-separated list to become
# reachable.  With multi-bootstrap support a node can join the network through
# any available bootstrapper, removing the single-bootstrap-node SPOF.
#
# Usage: wait_for_any_bootstrap "$BOOTSTRAP_PEERS"
#   BOOTSTRAP_PEERS is a comma-separated list of host:port pairs, e.g.
#     "node0:30303,node1:30303"
wait_for_any_bootstrap() {
    local peers_csv="$1"
    [[ -z "$peers_csv" ]] && return 0

    # Parse into arrays
    local hosts=()
    local ports=()
    IFS=',' read -ra PEER_LIST <<< "$peers_csv"
    for peer in "${PEER_LIST[@]}"; do
        peer=$(echo "$peer" | tr -d ' ')
        [[ -z "$peer" ]] && continue
        local host port
        host=$(echo "$peer" | rev | cut -d: -f2- | rev)
        port=$(echo "$peer" | rev | cut -d: -f1 | rev)
        hosts+=("$host")
        ports+=("$port")
    done

    if [[ ${#hosts[@]} -eq 0 ]]; then
        return 0
    fi

    log "Waiting for any bootstrap peer to become reachable: ${peers_csv}"

    local timeout=120
    while true; do
        for i in "${!hosts[@]}"; do
            if nc -z "${hosts[$i]}" "${ports[$i]}" 2>/dev/null; then
                log "Bootstrap peer ${hosts[$i]}:${ports[$i]} reachable"
                return 0
            fi
        done
        timeout=$((timeout - 1))
        if [[ $timeout -le 0 ]]; then
            error "Timeout waiting for bootstrap peers (tried: ${peers_csv})"
        fi
        sleep 1
    done
}

# Ensure runtime directory exists and is writable by the kora user.
# Docker named volumes inherit ownership from the image on first mount,
# but we verify here in case an external volume with different ownership
# is attached.
if [[ -d "$RUNTIME_DIR" ]]; then
    if [[ ! -w "$RUNTIME_DIR" ]]; then
        log "WARNING: runtime dir ${RUNTIME_DIR} is not writable, attempting chown..."
        chown -R "$(id -u):$(id -g)" "$RUNTIME_DIR" 2>/dev/null || \
            error "Cannot write to runtime dir ${RUNTIME_DIR}. Fix volume permissions."
    fi
else
    mkdir -p "$RUNTIME_DIR" 2>/dev/null || error "Cannot create runtime dir ${RUNTIME_DIR}"
fi
log "Runtime dir: ${RUNTIME_DIR} (writable)"

# Startup barrier: ensures all validators reach this point before any starts
# consensus. Each validator writes a marker file to a shared volume, then waits
# until the expected number of markers are present.
wait_for_barrier() {
    local count="$1"
    if [[ "$count" -le 0 || ! -d "$BARRIER_DIR" ]]; then
        return 0
    fi

    # Write our own marker
    touch "${BARRIER_DIR}/node${VALIDATOR_INDEX}.ready"
    log "Barrier: marked node${VALIDATOR_INDEX} ready (waiting for ${count} validators)"

    # Wait for all markers
    local timeout=120
    while true; do
        local ready
        ready=$(find "$BARRIER_DIR" -maxdepth 1 -name '*.ready' 2>/dev/null | wc -l | tr -d ' ')
        if [[ "$ready" -ge "$count" ]]; then
            log "Barrier: all ${count} validators ready, proceeding"
            return 0
        fi
        timeout=$((timeout - 1))
        if [[ $timeout -le 0 ]]; then
            log "Barrier: WARNING timeout after 120s (${ready}/${count} ready), proceeding anyway"
            return 0
        fi
        sleep 1
    done
}

case "$MODE" in
    setup)
        log "Running setup mode..."
        exec /usr/local/bin/keygen setup "$@"
        ;;

    dkg)
        log "Running DKG ceremony mode..."

        [[ -f "${SHARED_DIR}/peers.json" ]] || error "peers.json not found"
        [[ -f "${DATA_DIR}/validator.key" ]] || error "validator.key not found"

        if [[ -f "${DATA_DIR}/share.key" && -f "${DATA_DIR}/output.json" ]]; then
            log "DKG already completed (share.key exists)"
            exit 0
        fi

        if [[ "$IS_BOOTSTRAP" != "true" && -n "$BOOTSTRAP_PEERS" ]]; then
            wait_for_any_bootstrap "$BOOTSTRAP_PEERS"
        fi

        exec /usr/local/bin/kora \
            --config "$CONFIG_FILE" \
            --data-dir "$DATA_DIR" \
            --chain-id "$CHAIN_ID" \
            dkg \
            --peers "${SHARED_DIR}/peers.json" \
            "$@"
        ;;

    validator)
        log "Running validator mode..."

        [[ -f "${SHARED_DIR}/genesis.json" ]] || error "genesis.json not found"
        [[ -f "${DATA_DIR}/validator.key" ]] || error "validator.key not found"
        [[ -f "${DATA_DIR}/share.key" ]] || error "share.key not found (run DKG first)"
        [[ -f "${DATA_DIR}/output.json" ]] || error "output.json not found (run DKG first)"

        # Log key fingerprints so DKG key mismatches are immediately obvious
        SHARE_KEY_HASH=$(sha256sum "${DATA_DIR}/share.key" 2>/dev/null | cut -c1-16)
        OUTPUT_HASH=$(sha256sum "${DATA_DIR}/output.json" 2>/dev/null | cut -c1-16)
        log "DKG key fingerprints: share.key=${SHARE_KEY_HASH} output.json=${OUTPUT_HASH}"

        cp "${SHARED_DIR}/genesis.json" "${DATA_DIR}/" 2>/dev/null || true

        # Detect whether this is a first startup or a restart by checking
        # for the commit marker on the persistent /data volume. If it exists,
        # the node has finalized at least one block previously and does not
        # need the bootstrap peer or the startup barrier to proceed.
        # DO NOT use archive or QMDB paths -- those live on tmpfs (/runtime)
        # and are wiped on every container restart.
        if [[ -f "${DATA_DIR}/last_committed_digest" ]]; then
            log "Restart detected (last_committed_digest exists), skipping barrier and bootstrap wait"
        else
            # First startup -- wait for all validators to be ready before
            # starting consensus. This prevents height drift caused by
            # staggered startup: if the bootstrap node enters consensus
            # minutes before the others, it advances heights alone and
            # later leaders return None from propose() because they lack
            # the parent snapshot.
            wait_for_barrier "$VALIDATOR_COUNT"

            if [[ "$IS_BOOTSTRAP" != "true" && -n "$BOOTSTRAP_PEERS" ]]; then
                wait_for_any_bootstrap "$BOOTSTRAP_PEERS"
            fi
        fi

        touch "${DATA_DIR}/.ready"

        TX_GOSSIP=${TX_GOSSIP:-false}
        GOSSIP_FLAG=""
        if [[ "$TX_GOSSIP" == "true" ]]; then
            GOSSIP_FLAG="--tx-gossip"
            log "Transaction gossip ENABLED"
        else
            log "Transaction gossip DISABLED (set TX_GOSSIP=true to enable)"
        fi

        exec /usr/local/bin/kora \
            --config "$CONFIG_FILE" \
            --data-dir "$DATA_DIR" \
            --chain-id "$CHAIN_ID" \
            validator \
            --peers "${SHARED_DIR}/peers.json" \
            $GOSSIP_FLAG \
            "$@"
        ;;

    secondary)
        log "Running secondary peer mode..."

        [[ -f "${SHARED_DIR}/peers.json" ]] || error "peers.json not found"
        [[ -f "${DATA_DIR}/validator.key" ]] || error "validator.key not found"

        if [[ "$IS_BOOTSTRAP" != "true" && -n "$BOOTSTRAP_PEERS" ]]; then
            # Only wait for bootstrap on first startup. On restarts, the
            # P2P layer handles reconnection internally.
            if [[ ! -f "${DATA_DIR}/.bootstrap_done" ]]; then
                wait_for_any_bootstrap "$BOOTSTRAP_PEERS"
                touch "${DATA_DIR}/.bootstrap_done"
            else
                log "Restart detected (.bootstrap_done exists), skipping bootstrap peer wait"
            fi
        fi

        touch "${DATA_DIR}/.ready"

        exec /usr/local/bin/kora \
            --config "$CONFIG_FILE" \
            --data-dir "$DATA_DIR" \
            --chain-id "$CHAIN_ID" \
            secondary \
            --peers "${SHARED_DIR}/peers.json" \
            "$@"
        ;;

    *)
        exec "$MODE" "$@"
        ;;
esac
